name: Build and Deploy Storybook Workflow
on: [workflow_dispatch]
#on:
#  push:
#    paths: ["stories/**"]
env:
  VERSION: 'dev'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1
      with:
          persist-credentials: false
    - name: Install and Build 🔧 
      run: | # Install npm packages and build the Storybook files
          echo "building story book ${VERSION}"
          npm install
          npm run build-storybook
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
          repository-name: zeiders/webtools-storybook-pages
          # token: ${{ secrets.STORYBOOK_PUBLISHING_TOKEN }}
          branch: main # The branch the action should deploy to.
          folder: docs-build # The folder that the build-storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: docs # The folder that we serve our Storybook files from
